services:
  version-monitor:
    build: .
    container_name: version-monitor
    restart: always
    ports:
      - "3339:80"
    # We pass the .env file into the container
    env_file:
      - .env
    # Optional: ensure logs don't grow forever
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"